const aboutUsMainSection = document.createElement('div');
    const aboutUsPage = document.createElement('div');
        const aboutUsTitle = document.createElement('div');
        
export function addAboutUsMainSection() {
    //Add classes
    aboutUsMainSection.classList.add('aboutUsMainSection');
    aboutUsPage.classList.add('aboutUsPage');
    aboutUsTitle.classList.add('aboutUsTitle');

    //Inner HTML
    aboutUsPage.innerHTML = `
    <h1>About Our Journey</h1>
    <p>
    At Ramazzoti, we believe that pizza is more than just a dish – it's a symbol of community, love, and family. That's why our restaurant was born out of a passion for bringing people together through delicious, handmade pizza. From the crispy crust to the savory toppings, each pizza is made with fresh, high-quality ingredients that are carefully chosen to ensure the best taste possible. Our chefs have perfected the art of pizza making, combining traditional techniques with innovative twists to create unique and unforgettable flavors that keep our customers coming back for more.

We're not just any pizza restaurant – we're a family-owned and operated establishment that takes pride in creating a warm and welcoming atmosphere for our customers. From the moment you step inside, you'll be greeted with a smile and treated like a member of our family. Whether you're dining in, taking out, or ordering for delivery, we strive to make each experience a memorable one. Our goal is to make sure you leave with a smile on your face and a happy stomach.

At Ramazzoti, we're more than just a pizza restaurant – we're a part of the community. We believe in giving back to the people who have supported us over the years, and we're committed to using our success to make a positive impact. We support local charities and organizations that share our values, and we're always looking for ways to contribute to the community. We believe that by working together, we can create a brighter future for everyone. So come on down to Ramazzoti, where you'll enjoy delicious pizza, friendly service, and a sense of belonging.
    </p>
    <p>\n</p>
    <p>Generated by ChatGPT</p>
    `;

    //Appending
    aboutUsPage.appendChild(aboutUsTitle);
    aboutUsMainSection.appendChild(aboutUsPage);
    
    //Animating
    
    return aboutUsMainSection;
}